### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by pra2304tik** [ll0816/PythonDataStructure#1]
Traceback (most recent call last):
  File "xml.py", line 2, in <module>
    import xml.etree.ElementTree as ET
  File "C:\Users\ADMIN\Desktop\python3.1\xml.py", line 2, in <module>
    import xml.etree.ElementTree as ET
ModuleNotFoundError: No module named 'xml.etree'; 'xml' is not a package

**Comment by Shardul1707** [comment]
// Extracting Data from XML

//In this assignment you will write a Python program somewhat similar to http://www.py4e.com/code3/geoxml.py. The program will prompt for a URL, read the XML data from that URL using urllib and then parse and extract the comment counts from the XML data, compute the sum of the numbers in the file.

//We provide two files for this assignment. One is a sample file where we give you the sum for your testing and the other is the actual data you need to process for the assignment.

    Sample data: http://py4e-data.dr-chuck.net/comments_42.xml (Sum=2553)
    Actual data: http://py4e-data.dr-chuck.net/comments_751691.xml (Sum ends with 66)

//Code:


import urllib.request, urllib.parse, urllib.error
import xml.etree.ElementTree as ET
url=input('Enter-')
html=urllib.request.urlopen(url).read()
tree=ET.fromstring(html)
first=tree.findall('commentinfo/comments/comment')
print('comment count:',len(first))
sum=0
for item in first:
    print('Count:',item.find('count').text)
    sum=sum+int(count)
print('sum is:',sum)
.
.
.
.
What is wrong in this code? Help please!

**Comment by roannelafuente** [comment]
import urllib.request, urllib.parse, urllib.error
import xml.etree.ElementTree as ET

url = input("Enter location: ")
if len(url) < 1:
    url = "http://py4e-data.dr-chuck.net/comments_1517713.xml"
print ("Retrieving " + url)

xml = urllib.request.urlopen(url).read()
print ("Retrieved: " + str(len(xml)) + " characters")

tree = ET.fromstring(xml)

counts =  tree.findall('.//count')
print ("Count: " + str(len(counts)))

accumulator = 0

for count in counts:
    accumulator += int(count.text)

print ("Sum:" + str(accumulator))

I got this:
Enter location: http://py4e-data.dr-chuck.net/comments_1517713.xml
Retrieving http://py4e-data.dr-chuck.net/comments_1517713.xml
Retrieved: 4224 characters
Count: 50
Sum:2493
